### ISSUE TITLE
Any worth improvements?

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447-Foundation#1]
@radiantdinosaurs could you go over this repo and let me know what do you think. I'm interested in:

- Dose the folder structure make sense 
- Are the section in each README in the right order
- Is there something worth adding
- Maybe removing

What I'm not interested in

- spell check and grammar, since I'll send the text for proofing.

**Comment by radiantdinosaurs** [comment]
- In `0x4447-Foundation/programmer/` under the IDE setup, you might want to add in a rule to control the 80 column rule. In VS Code, this would be the `Word Wrap Column` rule, which would let the programmer visually see when it reaches that point. Also, you can say to set `Editor: Format On Save` to`true` (or checked) to make sure these rules apply when saving the file.

That's all that I see. The folder structure seemed good, the sections seemed to be in the right order, and I think everything provided enough information. It was helpful to me! But, as you said, spellcheck needs work.

**Comment by davidgatti** [comment]
I did not add `Format On Save` since it is IDE specific and more of a user preference.
